services:
  chatbot-builder-api:
    image: chatbot-builder-api
    build:
      context: .
      dockerfile: ChatbotBuilderApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      sqlserver:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AppDbContextConnection=Server=sqlserver;Database=master;User Id=sa;Password=cFj23uNY0lT&WP@t;TrustServerCertificate=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=cFj23uNY0lT&WP@t
      - ACCEPT_EULA=Y
    ports:
      - "1455:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
  
  chatbot-builder-executor:
    image: chatbot-builder-executor
    build:
      context: .
    ports:
      - "50051:50051"
    # Add environment variables
volumes:
  sqlserver-data: